name: Code coverage 

on:
  push:
    branches:
      - main
   
  pull_request:
    branches:
      - main
defaults:
  run:
    working-directory: main
jobs:
  code-coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and Test
      run: mvn test
    - name: Upload to Codecov
      uses: codecov/codecov-action@v1.0.13
      with:
        file: .src/target/site/jacoco/jacoco.xml
        flags: unittests
